name: Terraform

on:
  push:
    branches:
      - devbranch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip Lambda layer
        run: |
          mkdir -p Modules
          pip install -r requirements.txt -t Modules/.
          cd Modules
          zip -r ../requests.zip .

      - name: Zip Lambda function
        run: |
          cd lambda_function
          zip -r ../lambda_function.zip .
        working-directory: ${{ github.workspace }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.7.2"

      - name: Terraform Init
        run: terraform init

      - name: Update Terraform configuration
        run: |
          sed -i 's#filename = "lambda_function/lambda_function.zip"#filename = "lambda_function.zip"#' lambda_function.tf
          sed -i 's#source_code_hash = filebase64sha256("lambda_function/lambda_function.zip")#source_code_hash = filebase64sha256("lambda_function.zip")#' lambda_function.tf  

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
