name: Terraform

on:
  push:
    branches:
      - devbranch

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "ap-south-1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create directory and zip dependencies
        run: |
          mkdir Modules
          pip install -r requirements.txt -t Modules
          cd Modules
          zip -r ../dependencies.zip .
          cd ..

      - name: Upload dependencies to S3
        uses: jakejarvis/s3-sync-action@v2
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: your-bucket-name
          AWS_REGION: "ap-south-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "Modules"
